name: Transfers
on:
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: |
        wget -q https://github.com/jonntd/gclone/releases/download/v1.52.13/gclone_1.52.13_Linux_x86_64.gz
        gunzip gclone_1.52.13_Linux_x86_64.gz
        sudo mv gclone_1.52.13_Linux_x86_64 /usr/bin/gclone
        chmod +x /usr/bin/gclone
    #curl https://rclone.org/install.sh | sudo bash
    - name: Inject Rclone config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF
        mkdir -p /home/runner/accounts/ 
        cat >  /home/runner/accounts/1.json  << EOF
        ${{ secrets.SA1_CONF }}
        EOF
        cat >  /home/runner/accounts/2.json  << EOF
        ${{ secrets.SA2_CONF }}
        EOF
        cat >  /home/runner/accounts/3.json  << EOF
        ${{ secrets.SA3_CONF }}
        EOF
    - name: Rclone Synchronizing file
      run: |
        gclone copy ${{ secrets.FILE_PATH }}  --stats-log-level NOTICE -P --stats 20s --cache-chunk-total-size 20G --transfers=8 --drive-chunk-size 256M 
