name: Transfers
on:
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Rclone Install
      run: sudo wget -P /home/runner https://github.com/xinxin8816/heroku-ariang-21vianet/blob/master/rclone.zip && unzip /home/runner/rclone.zip && cd /home/runner && mv rclone /usr/bin/
    #curl https://rclone.org/install.sh | sudo bash
    - name: Inject Rclone config
      run: |
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${{ secrets.RCLONE_CONF }}
        EOF
        mkdir -p /home/runner/accounts/ 
        cat >  /home/runner/accounts/1.json  << EOF
        ${{ secrets.SA1_CONF }}
        EOF
        cat >  /home/runner/accounts/2.json  << EOF
        ${{ secrets.SA2_CONF }}
        EOF
        cat >  /home/runner/accounts/3.json  << EOF
        ${{ secrets.SA3_CONF }}
        EOF
    - name: Rclone Synchronizing file
      run: |
        rclone copy ${{ secrets.FILE_PATH }}  -v  --cache-chunk-total-size 20G --transfers=8 --drive-chunk-size 256M
